# Generated by Django 5.1.1 on 2024-10-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='created_view',
            new_name='created_at',
        ),
    ]
